# Generated by Django 4.2.5 on 2023-09-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Doctor_email', models.EmailField(max_length=100)),
                ('Doctor_education_shortlist', models.CharField(max_length=100)),
                ('Doctor_image', models.ImageField(upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.department')),
            ],
        ),
    ]
