# Generated by Django 4.2.5 on 2023-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spasalist',
            name='image',
            field=models.ImageField(default='images.png', upload_to='images/'),
        ),
    ]
