# Generated by Django 4.2.5 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_id',
            field=models.CharField(default='0000000000', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
