# Generated by Django 4.2.5 on 2023-09-28 17:23

import Appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_alter_appointment_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_id',
            field=models.CharField(default=Appointment.models.generate_short_uuid, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
