# Generated by Django 4.2.5 on 2023-09-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequrity', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
